### ISSUE TITLE
Amount of lines shown in IE/Firefox is 1 less than clamp prop value

### ISSUE THREAD

**Issue by thomasbottonari** [CezaryDanielNowak/React-dotdotdot#10] opened 2016-10-04 17:34 UTC
This component is working well for me in Chrome/Safari, but when I test in Firefox (for Mac) or IE11, it is truncating after 1 line instead of 2 when I have a clamp set to 2. In the meantime, I am using browser detection to add 1 to the clamp value when in either of those two browsers, but a fix would be ideal.

**Comment by kmcq** [comment] 2016-11-01 03:04
@kkwiatkowski #11 did not fix this issue. Do you have any ideas what would cause it? Thanks for adding IE and Firefox support!

**Comment by kieranmann** [comment] 2016-11-10 16:13
@thomasbottonari I also experienced this issue on a project I am working on. It was caused by the line-height not being equal to the height of the block. I would suggest increasing the line-height on the block so that the following is true. line-height \* lines = height

**Comment by puranjayjain** [comment] 2017-10-25 05:30
@CezaryDanielNowak can we have a new release after #11 ?

**Comment by Muskos** [comment] 2017-12-07 14:27
+1 IE/Firefox unstable

**Comment by Muskos** [comment] 2017-12-08 08:16
I caugth it. Dotdotdot work well in one case. I use it in creacct class and it work well. When I included it in simple function it didn't work.

**Comment by ogirniak** [comment] 2017-12-08 13:39
+1 IE/Firefox not work(
@Muskos can you please provide example when Dotdotdot works for you in IE/Firefox?

**Comment by Muskos** [comment] 2017-12-08 17:47
@ogirniak I create component  like this. 
```
class Content extends React.Component {
	render() {
	       return (
			<div>
				<Dotdotdot clamp={2}>
					{content.title}
				</Dotdotdot>
			</div>
		)
	}
}
```

**Comment by ogirniak** [comment] 2017-12-08 18:40
Unfortunately it's not working for me, but maybe the reason is that I'm trying to do it inside ag-grid.
Thank you!

**Comment by makker** [comment] 2017-12-18 09:23
I had the same issue. In my case I set the clamp value to 3, but in Edge and FF show only 2 lines. IE 11 and other browsers showed 3 lines. I had my CSS line height set in em. Changed the line height unit to px and all browsers started working fine.

**Comment by 2781** [comment] 2019-04-01 10:52
I had the same issue FF and IE show only 1 lines

 Dotdotdot clamp=3
h2 {contentTitle} /h2
/Dotdotdot

**Comment by nikita-zadorin** [comment] 2019-06-17 07:21
For me it works only if I add style with line-height on <Dotdotdot>:

const styles = theme => ({
  itemLine: {
    lineHeight: '22px',
  },
})

<Dotdotdot clamp={1} className={classes.itemLine}>
  <Typography className={classes.itemLine}>
    some text
  </Typography>
</Dotdotdot>

**Comment by nikita-zadorin** [comment] 2019-06-17 07:27
For me it works in FF only if I add style with line-height on Dotdotdot:
```
const styles = theme => ({
  itemLine: {
    lineHeight: '22px',
  },
})

<Dotdotdot clamp={1} className={classes.itemLine}>
  <Typography className={classes.itemLine}>
    some text
  </Typography>
</Dotdotdot>

**Comment by lhguerra** [comment] 2019-07-05 15:29
Any updates on this, guys? I have the same issue as @nikita-zadorin, and it is only fixed with line-height set to 1.

Ps.: not only in Firefox.

Edit: I got it. I was passing the title element as a child to the DotDotDot component, like this:
`<DotDotDot clamp={2} children={<Title>{title}</Title>} />`

It works fine when I add just the text to DotDotDot:
`<Title children={<DotDotDot clamp={2}>{title}</DotDotDot>} />`

Just a misuse from one who was used to the jQuery lib :joy:

**Comment by LightOri** [comment] 2019-07-18 12:23
Seems this issue was fixed in version 1.3.1
https://github.com/CezaryDanielNowak/React-dotdotdot#changelog

> round line-height value from computed float value - IE11 fix

I don't face this issue anymore.

**Comment by CezaryDanielNowak** [comment] 2019-07-18 15:46
![baby-success-meme-png-3](https://user-images.githubusercontent.com/621293/61472045-f358be00-a983-11e9-9fe6-70ddad74e09b.png)

**Closed as completed by CezaryDanielNowak** 2019-07-18 15:46 UTC
Labels: bug
