### ISSUE TITLE
IE 11 text-overflows when user enters extremely long words with no spaces

### ISSUE THREAD

**Issue by Jeowulf** [CezaryDanielNowak/React-dotdotdot#21] opened 2017-08-10 15:25 UTC
Edge case however when a user enters long words with no spaces the styling allows the text to escape the Dotdotdot element into neighboring elements

**Comment by kkwiatkowski** [comment] 2017-08-17 20:51
Possibly duplicate of #15

**Comment by CezaryDanielNowak** [comment] 2018-02-01 18:18
Please retest with latest version :)

**Closed as completed** 2018-02-01 18:18 UTC
